name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Debug ECR
      run: |
        echo "Registry: ${{ steps.login-ecr.outputs.registry }}"
        echo "Repository: ${{ secrets.ECR_REPOSITORY }}"
    - name: Build Docker Image
      run: |
        docker build -t capstone-app ./app

    - name: Tag Docker Image
      run: |
        docker tag capstone-app:latest ${{ steps.login-ecr.outputs.registry }}/capstone-app:latest

    - name: Push Docker Image
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/capstone-app:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name capstone-eks

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/

    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get svc
